Fix 401 error on cwe-id filter
projectdiscovery/cvemap pull request #79
Opened 2024-02-08 14:38 UTC by RamanaReddy0M

2024-02-12 10:33 UTC, ehsandeep requested changes
merge conflict

2024-02-26 14:15 UTC, tarunKoyalwar commented on pkg/runner/runner.go
> +		return query + subQuery
@RamanaReddy0M , we already have urlutil.OrderedParams so we should probably try to use it instead of manually building query with `&`

2024-02-26 14:15 UTC, tarunKoyalwar approved these changes
issue seems to be resolved after using urlutil.OrderedParams
```console
./cvemap -cwe CWE-216        


   ______   _____  ____ ___  ____  ____
  / ___/ | / / _ \/ __ \__ \/ __ \/ __ \
 / /__ | |/ /  __/ / / / / / /_/ / /_/ /
 \___/ |___/\___/_/ /_/ /_/\__,_/ .___/ 
                               /_/
					  

		projectdiscovery.io

[INF] Current cvemap version v0.0.4 (outdated)
╭────────────────┬──────┬──────────┬─────────┬─────────────────────────┬──────┬──────────╮
│ ID             │ CVSS │ SEVERITY │ EPSS    │ PRODUCT                 │ AGE  │ TEMPLATE │
├────────────────┼──────┼──────────┼─────────┼─────────────────────────┼──────┼──────────┤
│ CVE-2020-3514  │ 6.7  │ MEDIUM   │ 0.00042 │ firepower_management... │ 1222 │ ❌       │
│ CVE-2019-1911  │ 7.8  │ HIGH     │ 0.00042 │ hosted_collaboration... │ 1696 │ ❌       │
│ CVE-2019-12675 │ 8.8  │ HIGH     │ 0.00042 │ firepower_threat_def... │ 1607 │ ❌       │
│ CVE-2019-12674 │ 8.2  │ HIGH     │ 0.00042 │ firepower_threat_def... │ 1607 │ ❌       │
╰────────────────┴──────┴──────────┴─────────┴─────────────────────────┴──────┴──────────╯
```

2024-02-26 14:19 UTC, ehsandeep approved these changes

2024-02-26 14:20 UTC, merged